apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: myapp-build
spec:
  source:
    type: Git
    git:
      uri: "https://github.com/rifaterdemsahin/podhtml.git"
  strategy:
    type: Docker
