apiVersion: batch/v1
kind: CronJob
metadata:
  name: mycronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mycontainer
              image: busybox
              args:
                - /bin/sh
                - -c
                - date; echo Hello from the cron job
          restartPolicy: OnFailure
