apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  template:
    spec:
      containers:
        - name: mycontainer
          image: busybox
          args:
            - /bin/sh
            - -c
            - echo Hello World
      restartPolicy: Never
