apiVersion: v1  # The API version for the Service resource
kind: Service   # Defines the kind of resource, in this case, a Service
metadata:
  name: myservice  # The name of the Service resource
spec:
  selector:
    app: myapp   # The selector that matches pods with the label 'app: myapp'
  ports:
    - protocol: TCP     # The protocol used by the Service (typically TCP for most apps)
      port: 80          # The port exposed by the Service (clients will connect to this port)
      targetPort: 8080  # The port on the container where traffic should be routed
